### ISSUE TITLE
about ADNI dataset 

### ISSUE THREAD

**Issue by torressliu** [gml16/rl-medical#1]
After I applied for ADNI data set, I did not find the anatomical landmark label of corresponding MRI. Could you please tell me whether the dataset you used for training was marked by yourself ?

**Comment by gml16** [comment]
I asked @amiralansary about it, as he provided the data for my experiments. The landmarks have been annotated by expert clinicians and we unfortunately cannot share those publicly.

**Comment by lpengc** [comment]
could you please tell me how to generate the landmarks to txt files? 
For example, in `ADNI_002_S_0816_MR_MPR__GradWarp__B1_Correction__N3__Scaled_Br_20070217005829488_S18402_I40731.txt`, how to explain the first line `86,86,84`? Is this the corresponding to the physical coordinate in the CT image?
