### ISSUE TITLE
Large dataset training issue.

### ISSUE THREAD

**Issue by GYDDHPY** [gml16/rl-medical#10]
I'm sorry to disturb you.  
I want to use the project for a large datset. I have a large dataset which contain more than 3000 data for training. The training log shows that distance is not decrease but fluctuate a lot.  
I notice that the dataset you used in your article has fewer samples.  
Do I need to do some special modification to the code to make it suitable for large dataset training, like using longer episodes or something?
Looking forward to your reply.

**Comment by gml16** [comment]
Hi, that’s a very valid question. You may see some benefits from tuning the hyperparameters, even though the default ones in this repo should be reasonable. Assuming your data follows a similar distribution, you should see the model getting better in at most 100k steps in my experience. Make sure the epsilon value has reached its minimum value by the end of the experiment (if it’s closer to 1 the agents will move randomly).
