### ISSUE TITLE
Is there a way to change the view of the images?

### ISSUE THREAD

**Issue by Vathsan** [gml16/rl-medical#12]
Hi @gml16, I was able to train a model for a set of ultrasound images. I was wondering how to change the view of the images in the medical player. I want to get something like what you have done for [fetal head ultrasound](https://github.com/gml16/rl-medical/blob/master/doc/fetal_csp.mp4).

When I evaluate I get the following,

![Screenshot from 2023-04-13 12-44-04](https://user-images.githubusercontent.com/29911181/231853873-2b812b0b-cf64-4875-a8c7-f4b413411425.png)

but I would like to get something like this,

![Screenshot from 2023-04-13 12-47-37](https://user-images.githubusercontent.com/29911181/231854632-0c77fbd8-9f71-4882-ad71-c37a1273480e.png)

**Comment by gml16** [comment]
Hi Vathsan, thanks for the question. You have multiple ways to go about this. 

The best way would be to update the `viewer.py` file to swap the dimensions drawn. Feel free to submit a PR if you implement a way to view the images from different perspectives. 

Another hacky way would be to either rotate the images in your favourite image software, or directly swap the dimensions in the image reader [here](https://github.com/gml16/rl-medical/blob/c95ac1d982a3e258416c82c1351308cfd14ad14f/src/dataReader.py#L323). I don’t have my laptop with me so I can’t test it but that could do the trick. It would require to update the landmark coordinates and retrain the model.

**Comment by Vathsan** [comment]
Hi @gml16, thanks for the details. I'll try your suggestions and see if that works.
