### ISSUE TITLE
Landmark annotation

### ISSUE THREAD

**Issue by wang07380731** [gml16/rl-medical#14]
May I ask what tool doctors use to manually annotate your dataset?
 I tried Dolphin and itk snap, but their effects were not very good. 
This question is crucial to me, thank you

**Comment by gml16** [comment]
Hi, unfortunately I do not know what tool was used to annotate this dataset. I remember seeing MRIcron for similar tasks. You may find the answer to this in the appendix of related literature. Sorry I can’t be more of help.

**Comment by Vathsan** [comment]
I do not know what doctors use. But [3D Slicer](https://www.slicer.org/) is not a bad option to annotate datasets. I found it more helpful than itk snap

**Comment by wang07380731** [comment]
> I do not know what doctors use. But [3D Slicer](https://www.slicer.org/) is not a bad option to annotate datasets. I found it more helpful than itk snap

thank you , i will have a try.

**Comment by wang07380731** [comment]
> Hi, unfortunately I do not know what tool was used to annotate this dataset. I remember seeing MRIcron for similar tasks. You may find the answer to this in the appendix of related literature. Sorry I can’t be more of help.

thank you for your help

**Comment by wang07380731** [comment]
> I do not know what doctors use. But [3D Slicer](https://www.slicer.org/) is not a bad option to annotate datasets. I found it more helpful than itk snap

sorry, but does it support annotation of individual points? How can it export the annotation results in txt format, just like the dataset provided in this project?I seem not have found relevant information

**Comment by Vathsan** [comment]
I am not sure about your entire use case. You may try the [Markups](https://slicer.readthedocs.io/en/latest/user_guide/modules/markups.html) module and see if it fits you. It supports creating individual points and exporting as .fcsv file. You can search for **_Markups_** in the module finder.

**Comment by wang07380731** [comment]
> 

it works !thank you

**Comment by wang07380731** [comment]
> I am not sure about your entire use case. You may try the [Markups](https://slicer.readthedocs.io/en/latest/user_guide/modules/markups.html) module and see if it fits you. It supports creating individual points and exporting as .fcsv file. You can search for **_Markups_** in the module finder.

it works, thank you again.
