### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by Vathsan** [gml16/rl-medical#15]
Hey @gml16, I am working on adding data augmentation. Currently, I augment the data and place it inside the images folder. Is there any place that I could simply add the data augmentation logic within the code, so that it will be taken care of during runtime? Thanks

**Comment by gml16** [comment]
Hi @Vathsan, having a seperate script to augment the data is not a bad idea, especially if you want to run multiple trainings on the same augmented dataset. 

However, if you’d like to augment the dataset at runtime, you can edit the [data reader file](https://github.com/gml16/rl-medical/blob/master/src/dataReader.py). This is the file that loads the Nifti images and landmark ground truths. 

Any PR is more than welcome :)
