### ISSUE TITLE
Normalize and increase the contrast of the image

### ISSUE THREAD

**Issue by kong240** [gml16/rl-medical#17]
Hi, do you have any idea how to modify the coding on datareader.py so that the displayed image especially CT scans has higher contrast.
<img width="258" alt="Screenshot 2024-06-01 144356" src="https://github.com/gml16/rl-medical/assets/171409006/d466038a-e8f2-49b6-a751-7e7aeb6a9e7d"> (before)
<img width="215" alt="Screenshot 2024-06-01 144512" src="https://github.com/gml16/rl-medical/assets/171409006/bd31d047-f552-475e-983b-c68a06694392"> (after)

**Comment by gml16** [comment]
Hi @kong240, it depends if you want to change the underlying data of the `nii.gz` files, or if you only care about the visualisation on screen.

To change the visualisation contrast, you can update the [display()](https://github.com/gml16/rl-medical/blob/master/src/viewer.py#L86) method where we use `pyglet`.

If you want to change the actual data values that the RL agents train on, you can preprocess your `nii.gz` files to update the contrast. If you want to modify it during the training, on each image load,  you can update the [`decode()`](https://github.com/gml16/rl-medical/blob/master/src/dataReader.py#L317) method by updating how the image gets rescaled using `SimpleITK`.

Is this answering you question?

**Comment by kong240** [comment]
> Hi @kong240, it depends if you want to change the underlying data of the `nii.gz` files, or if you only care about the visualisation on screen.
> 
> To change the visualisation contrast, you can update the [display()](https://github.com/gml16/rl-medical/blob/master/src/viewer.py#L86) method where we use `pyglet`.
> 
> If you want to change the actual data values that the RL agents train on, you can preprocess your `nii.gz` files to update the contrast. If you want to modify it during the training, on each image load, you can update the [`decode()`](https://github.com/gml16/rl-medical/blob/master/src/dataReader.py#L317) method by updating how the image gets rescaled using `SimpleITK`.
> 
> Is this answering you question?

Thanks @gml16 , I will try it later and inform you if anything happens

**Comment by kong240** [comment]
Hi @gml16 , do you have any suggestion how to preprocess my nii.gz or change the underlying data of the nii.gz

**Comment by gml16** [comment]
The best suited tool for this is probably [SimpleITK](https://simpleitk.readthedocs.io/en/master/index.html)

**Comment by kong240** [comment]
Hi @gml16, what is the criteria for applying the 'play' task

**Comment by kong240** [comment]
Hi @gml16, may I know what is the criteria to use the 'play' task during testing
