### ISSUE TITLE
Image Testing

### ISSUE THREAD

**Issue by kong240** [gml16/rl-medical#18]
Hi @gml16 , may I know what is the criteria to use the 'play' task during testing. I mean can you show the example how to run the 'play' command for testing

**Comment by gml16** [comment]
Hi @kong240, thanks for the great question. I realised that the readme did not have instructions for this, and that there were some issues when using task mode `play` with multi agents. I have just pushed a commit to add the readme instructions and fix those bugs.

This is an example usage, as is now shown in the readme:
```
python DQN.py --task play --load 'data/models/BrainMRI/CommNet8agents.pt' --files 'data/filenames/image_files.txt' --file_type brain --landmarks 13 14 0 1 2 3 4 5 --model_name "CommNet"
```

Please let me know if you encounter any issues.

**Comment by kong240** [comment]
> Hi @kong240, thanks for the great question. I realised that the readme did not have instructions for this, and that there were some issues when using task mode `play` with multi agents. I have just pushed a commit to add the readme instructions and fix those bugs.
> 
> This is an example usage, as is now shown in the readme:
> 
> ```
> python DQN.py --task play --load 'data/models/BrainMRI/CommNet8agents.pt' --files 'data/filenames/image_files.txt' --file_type brain --landmarks 13 14 0 1 2 3 4 5 --model_name "CommNet"
> ```
> 
> Please let me know if you encounter any issues.

Ok, I will try it later, thanks for the update

**Comment by kong240** [comment]
Hi @gml16, why I got the below error while running the 'play' task:
Traceback (most recent call last):
  File "DQN.py", line 233, in <module>
    evaluator.play_n_episodes(fixed_spawn=args.fixed_spawn)
  File "C:\Users\ACER SWIFT 3\Documents\KKKZ4162 FYP1\rl-medical-master1\src\evaluator.py", line 45, in play_n_episodes
    score, start_dists, q_values, info = self.play_one_episode(render, fixed_spawn=fixed_spawn[j])
  File "C:\Users\ACER SWIFT 3\Documents\KKKZ4162 FYP1\rl-medical-master1\src\evaluator.py", line 87, in play_one_episode
    obs_stack, r, isOver, info = self.env.step(acts, q_values, isOver)
  File "C:\Users\ACER SWIFT 3\Documents\KKKZ4162 FYP1\rl-medical-master1\src\medical.py", line 873, in step
    current_st, reward, terminal, info = self.env.step(
  File "C:\Users\ACER SWIFT 3\Documents\KKKZ4162 FYP1\rl-medical-master1\src\medical.py", line 460, in step
    info[f"landmark_xpos_{i}"] = self._target_loc[i][0]
TypeError: 'NoneType' object is not subscriptable

**Comment by kong240** [comment]
Thank you @gml16, it really works for my project.
