### ISSUE TITLE
set seed & reproducible result

### ISSUE THREAD

**Issue by LeeKeyu** [gml16/rl-medical#3]
Hi,
May I ask how do you generate reproducible results as the environment randomly resets the state in each game? since I can't find how the random seeds can be manually set for each experiment.
Thank you in advance!

**Comment by gml16** [comment]
Thanks for the feedback :) I just added a `--seed` argument that makes both the environment and training reproducible. Let me know if I can help with anything else.

**Comment by LeeKeyu** [comment]
Yes, that solves the issue. Thanks for the quick reply!
