### ISSUE TITLE
about the evaluate command

### ISSUE THREAD

**Issue by wang07380731** [gml16/rl-medical#8]
When I run your code：“python DQN.py --task eval --load 'data/models/BrainMRI/Network3d8agents.pt' --files 'data/filenames/image_files.txt' 'data/filenames/landmark_files.txt' --file_type brain --landmarks 13 14 0 1 2 3 4 5 --model_name "Network3d"

The result of my error is as follows:
Traceback (most recent call last):
  File "DQN.py", line 234, in <module>
    evaluator.play_n_episodes(fixed_spawn=args.fixed_spawn)
  File "C:\Users\86159\Desktop\rl-medical-master\src\evaluator.py", line 44, in play_n_episodes
    score, start_dists, q_values, info = self.play_one_episode(render, fixed_spawn=fixed_spawn[j])
TypeError: 'NoneType' object is not subscriptable

Do you know why? This question may be very basic, because I am a novice.

**Comment by gml16** [comment]
Hi, thank you for bringing this to my attention. It is entirely a bug that slipped through. I have fixed it. Please pull from the master branch and do let me know if you encounter any other problem.

**Comment by wang07380731** [comment]
> Hi, thank you for bringing this to my attention. It is entirely a bug that slipped through. I have fixed it. Please pull from the master branch and do let me know if you encounter any other problem.

thank you, you are kind and high-level
