### ISSUE TITLE
Infer without landmarks

### ISSUE THREAD

**Issue by GYDDHPY** [gml16/rl-medical#9]
Hi, thank you for your great contribution.  
I want to use the model to predict landmarks for images without landmark ground truth file. However, it seems both the train and eval model require the landmark file. 
What should I do?
Looking forward to your reply.

**Comment by gml16** [comment]
Hi, that’s a good question. I believe I did not implement a nice way to run inference without the ground truth. As a workaround, you can use a dummy landmark file that had 0s. Otherwise, feel free to submit a PR to remove the requirement to have a landmark file, I’ll be happy to have a look :)

**Comment by GYDDHPY** [comment]
> Hi, that’s a good question. I believe I did not implement a nice way to run inference without the ground truth. As a workaround, you can use a dummy landmark file that had 0s. Otherwise, feel free to submit a PR to remove the requirement to have a landmark file, I’ll be happy to have a look :)

Thank you for your rapid reply. 
I will try to use zero landmark file to do inference at first.
